# Generated by Django 5.2 on 2025-04-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='hebrew_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='battle',
            name='hebrew_title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
