# Generated by Django 5.2 on 2025-04-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_battle_hebrew_description_battle_hebrew_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battle',
            name='date',
        ),
        migrations.AddField(
            model_name='battle',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='battle',
            name='year',
            field=models.IntegerField(choices=[(1939, '1939'), (1940, '1940'), (1941, '1941'), (1942, '1942'), (1943, '1943'), (1944, '1944'), (1945, '1945')], default=1),
            preserve_default=False,
        ),
    ]
