# Generated by Django 5.2 on 2025-04-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_remove_battle_date_battle_month_battle_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='hebrew_country',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
