# Generated by Django 5.2 on 2025-05-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_battle_end_month_battle_end_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='keywords',
            field=models.TextField(blank=True, help_text='הכנס תגיות מופרדות בפסיקים'),
        ),
    ]
