# Generated by Django 5.2 on 2025-05-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_battle_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soldier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_he', models.CharField(max_length=200, verbose_name='שם בעברית')),
                ('name_en', models.CharField(max_length=200, verbose_name='Name (EN)')),
                ('country_he', models.CharField(max_length=200, verbose_name='ארץ (עברית)')),
                ('country_en', models.CharField(max_length=200, verbose_name='Country (EN)')),
                ('lifeStory_he', models.TextField(verbose_name='קורות חיים (עברית)')),
                ('lifeStory_en', models.TextField(verbose_name='Life Story (EN)')),
                ('years', models.IntegerField(verbose_name='שנים')),
            ],
        ),
    ]
