# Generated by Django 5.2 on 2025-05-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_soldier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldier',
            name='years',
            field=models.CharField(max_length=200, verbose_name='שנים'),
        ),
    ]
