# Generated by Django 5.2 on 2025-05-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_alter_soldier_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='קישור לתמונה'),
        ),
    ]
