# Generated by Django 5.2 on 2025-05-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_soldier_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soldier',
            old_name='name_en',
            new_name='english_name',
        ),
        migrations.RenameField(
            model_name='soldier',
            old_name='name_he',
            new_name='hebrew_name',
        ),
        migrations.RenameField(
            model_name='soldier',
            old_name='image_url',
            new_name='image_link',
        ),
        migrations.RemoveField(
            model_name='soldier',
            name='country_en',
        ),
        migrations.RemoveField(
            model_name='soldier',
            name='country_he',
        ),
        migrations.RemoveField(
            model_name='soldier',
            name='lifeStory_en',
        ),
        migrations.RemoveField(
            model_name='soldier',
            name='lifeStory_he',
        ),
        migrations.RemoveField(
            model_name='soldier',
            name='years',
        ),
        migrations.AddField(
            model_name='soldier',
            name='Biography',
            field=models.TextField(default=0, verbose_name='קורות חיים'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soldier',
            name='hebrew_biography',
            field=models.TextField(default=0, verbose_name='קורות חיים'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soldier',
            name='hebrew_personal_details',
            field=models.TextField(default=0, verbose_name='פרטים אישיים'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soldier',
            name='personal_details',
            field=models.TextField(default=0, verbose_name='Personal Details'),
            preserve_default=False,
        ),
    ]
